import { Injectable } from '@nestjs/common';
import { FindingContext } from '../../../contracts/finding-context.interface';
import { FindingResult } from '../../../contracts/finding-result.interface';
import { FindingRule } from '../../../contracts/finding-rule.interface';
import { FindingCategory } from '../../../enums/finding-category.enum';
import { Severity } from '../../../enums/severity.enum';
import { AdvancedDnsRoutingAnalyzerService } from '../../../services/advanced-dns-routing-analyzer.service';

@Injectable()
export class DnssecValidationRule implements FindingRule {
  readonly id = 'dns.dnssec-validation';
  readonly name = 'DNSSEC Cryptographic Chain of Trust Validation';
  readonly category = FindingCategory.DNS_RECORD;

  constructor(
    private readonly routingAnalyzer: AdvancedDnsRoutingAnalyzerService,
  ) {}

  async evaluate(context: FindingContext): Promise<FindingResult[]> {
    const dns = context.snapshot.dns;
    if (!dns) {
      return [];
    }

    const dnssecStatus = dns.status?.dnssec;
    if (
      dnssecStatus === 'FAILED' ||
      dnssecStatus === 'TIMEOUT' ||
      dnssecStatus === 'SERVFAIL'
    ) {
      // WX-1020: Truth preservation on resolution failures
      return [];
    }

    const assessment = this.routingAnalyzer.analyzeDnssec(dns.dnssec);

    if (assessment.status === 'VALID') {
      return [];
    }

    if (assessment.status === 'EXPIRED_RRSIG') {
      return [
        {
          ruleId: this.id,
          title: 'Expired DNSSEC Signature (RRSIG)',
          description:
            'The authoritative DNSSEC RRSIG cryptographic signature for this domain has expired. Validating recursive DNS resolvers worldwide will reject resolution queries and return SERVFAIL.',
          category: this.category,
          severity: Severity.HIGH,
          confidence: 'AUTHORITATIVE',
          riskClassification: 'SECURITY_HARDENING_GAP',
          severityRationale:
            'Expired DNSSEC signatures cause widespread denial of service for any DNS clients utilizing DNSSEC-validating resolvers.',
          whatThisDoesNotProve:
            'This observation identifies an expired cryptographic signature in DNS; it does not indicate malicious tampering or domain takeover.',
          recommendations: [
            {
              title: 'Re-sign Zone and Refresh RRSIG Records',
              description:
                'Trigger an automated zone re-signing on authoritative nameservers to regenerate valid RRSIG signatures before TTL expiration.',
            },
          ],
        },
      ];
    }

    if (
      assessment.status === 'MISCONFIGURED' ||
      assessment.status === 'BOGUS'
    ) {
      return [
        {
          ruleId: this.id,
          title: 'Broken DNSSEC Chain of Trust (DS/DNSKEY Mismatch)',
          description:
            'The Delegation Signer (DS) record in the parent registry zone does not match the active DNSKEY / KSK in the child zone, breaking the cryptographic chain of trust.',
          category: this.category,
          severity: Severity.MEDIUM,
          confidence: 'AUTHORITATIVE',
          riskClassification: 'SECURITY_HARDENING_GAP',
          severityRationale:
            'Mismatched DNSSEC key tags or unsupported algorithms cause validating resolvers to classify the domain as BOGUS, failing lookup resolution.',
          whatThisDoesNotProve:
            'This finding detects a configuration inconsistency between registry and nameserver records; it does not prove active DNS spoofing.',
          recommendations: [
            {
              title: 'Synchronize DS Records with Parent Registrar',
              description:
                'Update the DS record at the domain registrar with the active Key Signing Key (KSK) tag and digest generated by your DNS provider.',
            },
          ],
        },
      ];
    }

    // Unsigned zone
    return [
      {
        ruleId: this.id,
        title: 'DNSSEC Not Configured (Unsigned Zone)',
        description:
          'Authoritative DNS records for this domain do not include DNSSEC cryptographic signatures (RFC 4033). DNS responses are vulnerable to on-path tampering and cache poisoning in transit.',
        category: this.category,
        severity: Severity.LOW,
        confidence: 'AUTHORITATIVE',
        riskClassification: 'SECURITY_HARDENING_GAP',
        severityRationale:
          'Without DNSSEC, intermediate DNS caches cannot cryptographically authenticate that responses originated unmodified from authoritative nameservers.',
        whatThisDoesNotProve:
          'This finding notes the absence of DNSSEC signatures; it does not demonstrate that DNS responses have been intercepted or poisoned.',
        recommendations: [
          {
            title: 'Enable DNSSEC on Authoritative DNS Provider',
            description:
              'Enable DNSSEC signing on your authoritative DNS host (e.g. Cloudflare, Route 53, NS1) and publish the generated DS record at your registrar.',
          },
        ],
      },
    ];
  }
}
