export enum TopologyLayer {
  EDGE = 'EDGE',
  GATEWAY = 'GATEWAY',
  APPLICATION = 'APPLICATION',
  RUNTIME = 'RUNTIME',
  INTEGRATION = 'INTEGRATION',
  SECURITY = 'SECURITY',
  PLATFORM = 'PLATFORM',
}
