/**
 * GX-R010 — First Meaningful Intelligence & Progressive Disclosure Contract
 *
 * Phase: Guest Experience Redesign (GX-R)
 * Ticket: GX-R010
 * Type: UX / Architecture / Intelligence Presentation / Progressive Disclosure Contract
 * Priority: P0 — Critical Intelligence Canvas
 * Depends on: GX-R001 → GX-R009
 * Unblocks: GX-R011 — Findings & Attention Model
 * Status: FROZEN_INTELLIGENCE_DISCLOSURE_CONTRACT
 *
 * Objective:
 * Define the first actual intelligence the guest sees after discovery completion.
 *
 * Frozen Principle:
 * "Meaning before detail."
 */

import {
  CANONICAL_INFRASTRUCTURE_CATEGORIES,
} from './gx-r002-information-architecture.contract.ts';

export const GX_R010_TICKET_ID = 'GX-R010';
export const GX_R010_PHASE = 'Guest Experience Redesign';
export const GX_R010_STATUS = 'FROZEN_INTELLIGENCE_DISCLOSURE_CONTRACT';

export const GX_R010_FROZEN_PRINCIPLE = 'Meaning before detail.';

export const GX_R010_CERTIFICATION_GATE_STATEMENT =
  'A guest immediately understands what Nebula has learned about the domain, why it matters, and where to look next — without being overwhelmed by raw observations.';

/**
 * 1. Six-Level Progressive Disclosure Ladder
 */
export interface MeaningfulProgressiveDisclosureLevel {
  level: number;
  name: string;
  keySurfaces: string[];
  cognitivePurpose: string;
}

export const PROGRESSIVE_DISCLOSURE_LADDER: readonly MeaningfulProgressiveDisclosureLevel[] = [
  {
    level: 0,
    name: 'Orientation',
    keySurfaces: ['Domain Context Anchor', 'UNDERSTANDING Status', 'Snapshot Timestamp'],
    cognitivePurpose: 'Establishes unwavering reference to the investigated target domain.',
  },
  {
    level: 1,
    name: 'Meaning (Current Understanding)',
    keySurfaces: ['Executive Brief Narrative', 'Synthesized Interpretation'],
    cognitivePurpose: 'Answers "What does Nebula currently understand about this domain?" in plain prose.',
  },
  {
    level: 2,
    name: 'Attention (What Matters Now)',
    keySurfaces: ['Actionable Observations', 'Significance Breakdown', 'Understand why → CTA'],
    cognitivePurpose: 'Highlights high-priority findings and explains architectural significance.',
  },
  {
    level: 3,
    name: 'Architecture & Secondary Observations',
    keySurfaces: ['Semantic Observation Groups', '8-Category Infrastructure Matrix'],
    cognitivePurpose: 'Exposes structural topology across Edge, DNS, TLS, Web Server, App, Platform, Host, Mail.',
  },
  {
    level: 4,
    name: 'Evidence Preview',
    keySurfaces: ['Contextual Investigation Doorway', 'Observed Signal Summary'],
    cognitivePurpose: 'Bridges cognitive understanding to specific telemetry evidence.',
  },
  {
    level: 5,
    name: 'Deep Investigation',
    keySurfaces: ['Contextual Investigation Drawer', 'Raw Collector Payloads', 'Cryptographic Hashes'],
    cognitivePurpose: 'Provides full evidentiary audit trail upon deliberate guest interaction.',
  },
] as const;

/**
 * 2. Eight Canonical Infrastructure Categories (from GX-R002)
 */
export const GX_R010_CANONICAL_INFRASTRUCTURE_CATEGORY_NAMES = [
  'Edge',
  'Web Server',
  'Application',
  'Platform',
  'Hosting',
  'DNS',
  'TLS',
  'Mail',
] as const;

export const GX_R010_INFRASTRUCTURE_SPECS = CANONICAL_INFRASTRUCTURE_CATEGORIES;

/**
 * 3. Quiet & Healthy State Contracts
 */
export const QUIET_STATE_CONTRACT = {
  primaryHeadline: 'Infrastructure appears stable.',
  subtext: 'The observed perimeter satisfies baseline cryptographic, routing, and header standards.',
  prohibitedActions: [
    'Manufacturing artificial warnings or low-severity alerts',
    'Inflating risk to prompt user upgrades',
    'Fabricating synthetic security vulnerabilities',
  ],
} as const;

/**
 * 4. Contextual Investigation CTA
 */
export const CANONICAL_INVESTIGATION_CTA = 'Understand why →';
export const PROHIBITED_INVESTIGATION_CTAS = [
  'View Details',
  'See Full Report',
  'Inspect Finding',
  'Run Analysis',
  'Scan Again',
  'Upgrade to Inspect',
] as const;

/**
 * 5. Strict Anti-Fabrication Contract
 */
export const ANTI_FABRICATION_INVARIANTS = [
  'UI renders direct canonical Executive Brief paragraphs without editorial synthesis drift.',
  'Finding severities strictly match canonical backend scale (Critical, High, Medium, Low, Info).',
  'No arbitrary numerical posture scores (e.g. 94/100) unless present in canonical backend model.',
  'No fake check counters (e.g. "127 checks passed").',
  'No synthetic observations generated by client presentation layers.',
] as const;

/**
 * 6. Ten Explicitly Rejected Anti-Patterns
 */
export const EXPLICITLY_REJECTED_INTELLIGENCE_PATTERNS = [
  'KPI dashboard wall (e.g. "94 / 100 · 17 findings · 8 technologies")',
  'Scan report check count (e.g. "127 checks completed")',
  'Security sales funnel (e.g. "3 vulnerabilities found → Upgrade")',
  'Evidence-first presentation (huge raw DNS/TLS/HTTP tables immediately on completion)',
  'AI theater (e.g. "AI discovered something amazing!")',
  'Artificial severity inflation (turning harmless baseline observations into warnings)',
  'Card explosion (every sentence enclosed in a separate rounded box)',
  'Infinite scroll report architecture',
  'Workspace lock wall (e.g. "Sign up to view findings", "Create account to unlock")',
  'Fake numerical posture scores computed decoratively in the UI',
] as const;

/**
 * Meaningful Intelligence Configuration Validator
 */
export interface MeaningfulIntelligenceConfig {
  hasKpiWall: boolean;
  hasScanReportCounters: boolean;
  hasSalesFunnelUpgradeWall: boolean;
  isEvidenceFirst: boolean;
  hasAiTheaterGimmick: boolean;
  hasArtificialSeverity: boolean;
  hasInfiniteScroll: boolean;
  hasLockWall: boolean;
  usesCanonicalExecutiveBrief: boolean;
  meaningPrecedesEvidence: boolean;
  exposesAllEightCategories: boolean;
  preservesContextOnDrawerClose: boolean;
  supportsQuietHealthyState: boolean;
}

export interface MeaningfulIntelligenceResult {
  valid: boolean;
  violation?: string;
}

export function validateMeaningfulIntelligence(
  config: MeaningfulIntelligenceConfig
): MeaningfulIntelligenceResult {
  if (config.hasKpiWall) {
    return {
      valid: false,
      violation: 'KPI dashboard wall violates GX-R010 editorial restraint.',
    };
  }

  if (config.hasScanReportCounters) {
    return {
      valid: false,
      violation: 'Scan report check counters violate meaningful intelligence contract.',
    };
  }

  if (config.hasSalesFunnelUpgradeWall || config.hasLockWall) {
    return {
      valid: false,
      violation: 'Forced upgrade lock walls violate the open guest intelligence boundary.',
    };
  }

  if (config.isEvidenceFirst) {
    return {
      valid: false,
      violation: 'Evidence-first presentation violates "Meaning before detail".',
    };
  }

  if (config.hasAiTheaterGimmick) {
    return {
      valid: false,
      violation: 'AI theater messaging is strictly prohibited.',
    };
  }

  if (config.hasArtificialSeverity) {
    return {
      valid: false,
      violation: 'Artificial severity inflation violates canonical truth invariants.',
    };
  }

  if (config.hasInfiniteScroll) {
    return {
      valid: false,
      violation: 'Infinite scroll report layout violates the bounded workspace architecture.',
    };
  }

  if (!config.usesCanonicalExecutiveBrief) {
    return {
      valid: false,
      violation: 'Current Understanding must use canonical Executive Brief data directly.',
    };
  }

  if (!config.meaningPrecedesEvidence) {
    return {
      valid: false,
      violation: 'Disclosure ladder must place Meaning and Significance before Evidence.',
    };
  }

  if (!config.exposesAllEightCategories) {
    return {
      valid: false,
      violation: 'Infrastructure Matrix must expose all 8 canonical infrastructure categories.',
    };
  }

  if (!config.supportsQuietHealthyState) {
    return {
      valid: false,
      violation: 'Must support calm quiet state when infrastructure is healthy.',
    };
  }

  if (!config.preservesContextOnDrawerClose) {
    return {
      valid: false,
      violation: 'Closing contextual investigation drawer must restore exact previous context.',
    };
  }

  return { valid: true };
}

/**
 * Certification Gate Verifier for GX-R010
 */
export function verifyGXR010CertificationGate(statement: string): {
  passed: boolean;
  canonicalStatement: string;
  similarityRatio: number;
} {
  const normalizedCandidate = statement.toLowerCase().replace(/[^a-z0-9]/g, ' ');
  const normalizedCanonical = GX_R010_CERTIFICATION_GATE_STATEMENT.toLowerCase().replace(/[^a-z0-9]/g, ' ');

  const candidateTokens = new Set(normalizedCandidate.split(/\s+/).filter(Boolean));
  const canonicalTokens = new Set(normalizedCanonical.split(/\s+/).filter(Boolean));

  let overlap = 0;
  for (const token of candidateTokens) {
    if (canonicalTokens.has(token)) {
      overlap++;
    }
  }

  const similarity = overlap / Math.max(canonicalTokens.size, candidateTokens.size);

  return {
    passed: similarity >= 0.85,
    canonicalStatement: GX_R010_CERTIFICATION_GATE_STATEMENT,
    similarityRatio: similarity,
  };
}
