import { ApiProperty } from '@nestjs/swagger';
import { TimelineEventDto } from './timeline-event.dto';

export class TimelineRuleDetailDto {
  @ApiProperty({ example: 'http.missing-hsts' })
  ruleId!: string;

  @ApiProperty({ example: '1.0.0' })
  ruleVersion!: string;

  @ApiProperty({ example: 'Missing HSTS Header Rule' })
  name!: string;

  @ApiProperty({
    example: 'Detects absent Strict-Transport-Security security headers.',
  })
  description!: string;
}

export class TimelineDetailDto {
  @ApiProperty({ type: TimelineEventDto })
  event!: TimelineEventDto;

  @ApiProperty({ type: TimelineRuleDetailDto, nullable: true })
  rule!: TimelineRuleDetailDto | null;

  @ApiProperty({
    example: [],
    description: 'Canonical observations evaluated for this event.',
  })
  observations!: any[];

  @ApiProperty({
    example: [],
    description: 'Raw evidence artifacts backing this event.',
  })
  evidence!: any[];

  @ApiProperty({
    example: [],
    description: 'Related findings generated by or linked to this event.',
  })
  relatedFindings?: any[];

  @ApiProperty({
    example: [],
    description: 'Related infrastructure assets involved in this change.',
  })
  relatedAssets?: any[];

  @ApiProperty({
    description:
      'Detailed component diff between previous and current snapshots.',
  })
  changeDiff?: {
    technologies: {
      added: string[];
      removed: string[];
      modified: any[];
      unchanged: string[];
    };
    dns: {
      added: string[];
      removed: string[];
      modified: any[];
      unchanged: string[];
    };
    headers: {
      added: any[];
      removed: any[];
      modified: any[];
      unchanged: any[];
    };
    certificates: {
      added: string[];
      removed: string[];
      modified: any[];
      unchanged: string[];
    };
    assets: {
      added: string[];
      removed: string[];
      modified: any[];
      unchanged: string[];
    };
  };

  @ApiProperty({
    example: 'snap-prev-uuid',
    nullable: true,
    description: 'Previous infrastructure snapshot ID.',
  })
  previousSnapshotId!: string | null;

  @ApiProperty({
    example: 'snap-curr-uuid',
    nullable: true,
    description: 'Current infrastructure snapshot ID.',
  })
  currentSnapshotId!: string | null;

  @ApiProperty({
    nullable: true,
    description: 'Previous infrastructure snapshot metadata.',
  })
  previousSnapshot?: any;

  @ApiProperty({
    nullable: true,
    description: 'Current infrastructure snapshot metadata.',
  })
  currentSnapshot?: any;
}
